import random,time,os
Red = "\033[0;31m"
Green = "\033[0;32m"
White = "\033[0;37m" 
red = "\033[0;91m"
green = "\033[0;92m"
yellow = "\033[0;93m"
blue = "\033[0;94m"
magenta = "\033[0;95m"
cyan = "\033[0;96m"
white = "\033[0;97m"
blue_back="\033[0;44m"
orange_back="\033[0;43m"
red_back="\033[0;41m"
grey_back="\033[0;40m"

def clear():
  os.system("clear")

def wait(x):
  time.sleep(x)

print(blue+"A long time ago, in a galaxy far far away....")
time.sleep(3)
print(yellow+"      _                                       ")  
print(yellow+"  ___| |_ __ _ _ __  __      ____ _ _ __ ___  ")
print(yellow+" / __| __/ _` | '__| \ \ /\ / / _` | '__/ __| ")
print(yellow+" \__ \ || (_| | |     \ V  V / (_| | |  \__ \ ")
print(yellow+" |___/\__\__,_|_|      \_/\_/ \__,_|_|  |___/ ")
wait(1.5)
clear()
print(yellow+"      _                                       ")  
print(yellow+"  ___| |_ __ _ _ __  __      ____ _ _ __ ___  ")
print(yellow+" / __| __/ _` | '__| \ \ /\ / / _` | '__/ __| ")
print(yellow+" \__ \ || (_| | |     \ V  V / (_| | |  \__ \ ")
print(yellow+" |___/\__\__,_|_|      \_/\_/ \__,_|_|  |___/ ")
wait(1.5)
clear()
print(yellow+"      _                                       ")  
print(yellow+"  ___| |_ __ _ _ __                           ")
print(yellow+" / __| __/ _` | '__|                          ")
print(yellow+" \__ \ || (_| | |    __      ____ _ _ __ ___  ")
print(yellow+" |___/\__\__,_|_|    \ \ /\ / / _` | '__/ __| ")
print(yellow+"                      \ V  V / (_| | |  \__ \ ")
print(yellow+"                       \_/\_/ \__,_|_|  |___/ ")
wait(.5)
clear()
print(yellow+"      _                                       ")  
print(yellow+"  ___| |_ __ _ _ __                           ")
print(yellow+" / __| __/ _` | '__|                          ")
print(yellow+" \__ \ || (_| | |                             ")
print(yellow+" |___/\__\__,_|_|                             ")
print(yellow+"                     __      ____ _ _ __ ___  ")
print(yellow+"                     \ \ /\ / / _` | '__/ __| ")
print(yellow+"                      \ V  V / (_| | |  \__ \ ")
print(yellow+"                       \_/\_/ \__,_|_|  |___/ ")
wait(.5)
clear()
print(yellow+"      _                                       ")  
print(yellow+"  ___| |_ __ _ _ __                           ")
print(yellow+" / __| __/ _` | '__|                          ")
print(yellow+" \__ \ || (_| | |                             ")
print(yellow+" |___/\__\__,_|_|                             ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                     __      ____ _ _ __ ___  ")
print(yellow+"                     \ \ /\ / / _` | '__/ __| ")
print(yellow+"                      \ V  V / (_| | |  \__ \ ")
print(yellow+"                       \_/\_/ \__,_|_|  |___/ ")
wait(.5)
clear()
print(yellow+"      _                                       ")  
print(yellow+"  ___| |_ __ _ _ __                           ")
print(yellow+" / __| __/ _` | '__|                          ")
print(yellow+" \__ \ || (_| | |                             ")
print(yellow+" |___/\__\__,_|_|                             ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                     __      ____ _ _ __ ___  ")
print(yellow+"                     \ \ /\ / / _` | '__/ __| ")
print(yellow+"                      \ V  V / (_| | |  \__ \ ")
print(yellow+"                       \_/\_/ \__,_|_|  |___/ ")
wait(.5)
clear()
print(yellow+"      _                                       ")  
print(yellow+"  ___| |_ __ _ _ __                           ")
print(yellow+" / __| __/ _` | '__|                          ")
print(yellow+" \__ \ || (_| | |                             ")
print(yellow+" |___/\__\__,_|_|                             ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                                              ")
print(yellow+"                     __      ____ _ _ __ ___  ")
print(yellow+"                     \ \ /\ / / _` | '__/ __| ")
print(yellow+"                      \ V  V / (_| | |  \__ \ ")
print(yellow+"                       \_/\_/ \__,_|_|  |___/ ")
wait(.5)
clear()
print(yellow+"           _                                       ")  
print(yellow+"       ___| |_ __ _ _ __                           ")
print(yellow+"      / __| __/ _` | '__|                          ")
print(yellow+"      \__ \ || (_| | |                             ")
print(yellow+"      |___/\__\__,_|_|                             ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                          __      ____ _ _ __ ___  ")
print(yellow+"                          \ \ /\ / / _` | '__/ __| ")
print(yellow+"                           \ V  V / (_| | |  \__ \ ")
print(yellow+"                            \_/\_/ \__,_|_|  |___/ ")
wait(.5)
clear()
print(yellow+"                 _                                 ")  
print(yellow+"             ___| |_ __ _ _ __                     ")
print(yellow+"            / __| __/ _` | '__|                    ")
print(yellow+"            \__ \ || (_| | |                       ")
print(yellow+"            |___/\__\__,_|_|                       ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                                                   ")
print(yellow+"                          __      ____ _ _ __ ___  ")
print(yellow+"                          \ \ /\ / / _` | '__/ __| ")
print(yellow+"                           \ V  V / (_| | |  \__ \ ")
print(yellow+"                            \_/\_/ \__,_|_|  |___/ ")
wait(.5)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"           > \ | |   |  _  ||    /                             ")
print(yellow+"           __/ |_|   |_| |_||_|\__                             ")
print(yellow+"                                                               ")
print(yellow+"                                                               ")
print(yellow+"                                                               ")
print(yellow+"                                                               ")
print(yellow+"                                                               ")
print(yellow+"                                                               ")
print(yellow+"                                                               ")
print(yellow+"                             __    _   ___   ____   __         ")
print(yellow+"                               |  | | / _ \ |  _ \ / _         ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.5)
clear()

print(yellow+"            ________   ___   ____                           ")
print(yellow+"           / __   __| / _ \ |  _ \                          ")
print(yellow+"     ______> \ | |   |  _  ||    /_______                   ")
print(yellow+"      _______/ |_|   |_| |_||_|\_________                   ")
print(yellow+"     /                                                      ")
print(yellow+"                                                            ")
print(yellow+"                                                            ")
print(yellow+"                                                            ")
print(yellow+"                                                            ")
print(yellow+"                                                            ")
print(yellow+"                                                            ")
print(yellow+"                    ___________    _   ___   ____   _______/")
print(yellow+"                    _________  |  | | / _ \ |  _ \ / _______")
print(yellow+"                             | |/\| ||  _  ||    / > \      ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/      ")
wait(.5)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /_____________________        ")
print(yellow+"    / _______/ |_|   |_| |_||_|\_______________________        ")
print(yellow+"   / /                                                         ")
print(yellow+"  | |                                                          ")
print(yellow+"  | |                                                          ")
print(yellow+"                                                               ")
print(yellow+"                                                            | |")
print(yellow+"                                                            | |")
print(yellow+"                                                            | |")
print(yellow+"             __________________    _   ___   ____   _______/ / ")
print(yellow+"             ________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.5)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |                                                       | |")
print(yellow+"  | |                                                       | |")
print(yellow+"  | |                                                       | |")
print(yellow+"  | |                                                       | |")
print(yellow+"  | |                                                       | |")
print(yellow+"  | |                                                       | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.5)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____"+yellow+"                                            | |")
print(yellow+"  | |     "+blue+"|  ___"+yellow+"                                            | |")
print(yellow+"  | |     "+blue+"| |_  "+yellow+"                                            | |")
print(yellow+"  | |     "+blue+"|  _| "+yellow+"                                            | |")
print(yellow+"  | |     "+blue+"|_|   "+yellow+"                                            | |")
print(yellow+"  | |     "+blue+"      "+yellow+"                                            | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.25)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____ _ "+yellow+"                                         | |")
print(yellow+"  | |     "+blue+"|  ___(_)"+yellow+"                                         | |")
print(yellow+"  | |     "+blue+"| |_  | |"+yellow+"                                         | |")
print(yellow+"  | |     "+blue+"|  _| | |"+yellow+"                                         | |")
print(yellow+"  | |     "+blue+"|_|   |_|"+yellow+"                                         | |")
print(yellow+"  | |     "+blue+"         "+yellow+"                                         | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.25)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____ _       "+yellow+"                                   | |")
print(yellow+"  | |     "+blue+"|  ___(_) __ _ "+yellow+"                                   | |")
print(yellow+"  | |     "+blue+"| |_  | |/ _` |"+yellow+"                                   | |")
print(yellow+"  | |     "+blue+"|  _| | | (_| |"+yellow+"                                   | |")
print(yellow+"  | |     "+blue+"|_|   |_|\__, |"+yellow+"                                   | |")
print(yellow+"  | |     "+blue+"         |___/ "+yellow+"                                   | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.25)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____ _       _     "+yellow+"                             | |")
print(yellow+"  | |     "+blue+"|  ___(_) __ _| |__  "+yellow+"                             | |")
print(yellow+"  | |     "+blue+"| |_  | |/ _` | '_ \ "+yellow+"                             | |")
print(yellow+"  | |     "+blue+"|  _| | | (_| | | | |"+yellow+"                             | |")
print(yellow+"  | |     "+blue+"|_|   |_|\__, |_| |_|"+yellow+"                             | |")
print(yellow+"  | |     "+blue+"         |___/       "+yellow+"                             | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.25)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____ _       _     _   "+yellow+"                         | |")
print(yellow+"  | |     "+blue+"|  ___(_) __ _| |__ | |_ "+yellow+"                         | |")
print(yellow+"  | |     "+blue+"| |_  | |/ _` | '_ \| __|"+yellow+"                         | |")
print(yellow+"  | |     "+blue+"|  _| | | (_| | | | | |_ "+yellow+"                         | |")
print(yellow+"  | |     "+blue+"|_|   |_|\__, |_| |_|\__|"+yellow+"                         | |")
print(yellow+"  | |     "+blue+"         |___/           "+yellow+"                         | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.25)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____ _       _     _     ____  "+yellow+"                 | |")
print(yellow+"  | |     "+blue+"|  ___(_) __ _| |__ | |_  / ___| "+yellow+"                 | |")
print(yellow+"  | |     "+blue+"| |_  | |/ _` | '_ \| __| \___ \ "+yellow+"                 | |")
print(yellow+"  | |     "+blue+"|  _| | | (_| | | | | |_   ___) |"+yellow+"                 | |")
print(yellow+"  | |     "+blue+"|_|   |_|\__, |_| |_|\__| |____/ "+yellow+"                 | |")
print(yellow+"  | |     "+blue+"         |___/                   "+yellow+"                 | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.25)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____ _       _     _     ____  _ "+yellow+"               | |")
print(yellow+"  | |     "+blue+"|  ___(_) __ _| |__ | |_  / ___|(_)"+yellow+"               | |")
print(yellow+"  | |     "+blue+"| |_  | |/ _` | '_ \| __| \___ \| |"+yellow+"               | |")
print(yellow+"  | |     "+blue+"|  _| | | (_| | | | | |_   ___) | |"+yellow+"               | |")
print(yellow+"  | |     "+blue+"|_|   |_|\__, |_| |_|\__| |____/|_|"+yellow+"               | |")
print(yellow+"  | |     "+blue+"         |___/                     "+yellow+"               | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(.25)
clear()
print(yellow+"            ________   ___   ____                              ")
print(yellow+"           / __   __| / _ \ |  _ \                             ")
print(yellow+"     ______> \ | |   |  _  ||    /__________________________   ")
print(yellow+"    / _______/ |_|   |_| |_||_|\___________________________ \  ")
print(yellow+"   / /                                                     \ \ ")
print(yellow+"  | |     "+blue+" _____ _       _     _     ____  _           "+yellow+"     | |")
print(yellow+"  | |     "+blue+"|  ___(_) __ _| |__ | |_  / ___|(_)_ __ ___  "+yellow+"     | |")
print(yellow+"  | |     "+blue+"| |_  | |/ _` | '_ \| __| \___ \| | '_ ` _ \ "+yellow+"     | |")
print(yellow+"  | |     "+blue+"|  _| | | (_| | | | | |_   ___) | | | | | | |"+yellow+"     | |")
print(yellow+"  | |     "+blue+"|_|   |_|\__, |_| |_|\__| |____/|_|_| |_| |_|"+yellow+"     | |")
print(yellow+"  | |     "+blue+"         |___/                               "+yellow+"     | |")
print(yellow+"   \ \_________________________    _   ___   ____   _______/ / ")
print(yellow+"    \________________________  |  | | / _ \ |  _ \ / _______/  ")
print(yellow+"                             | |/\| ||  _  ||    / > \         ")
print(yellow+"                              \_/\_/ |_| |_||_|\_\|__/         ")
wait(1.5)
print("")
print(white+"   "+blue_back+"         __           ______     _____     ______ ____      "+white)
print(white+"   "+blue_back+"        / /  __ __   / __/ /__  / ___/__ _/ /_  // __/      "+white)
print(white+"   "+blue_back+"       / _ \/ // /  / _// / _ \/ /__/ _ `/ //_ </__ \       "+white)
print(white+"   "+blue_back+"      /_.__/\_, /  /_/ /_/\___/\___/\_,_/_/____/____/       "+white)
print(white+"   "+blue_back+"           /___/                                            "+white)
